### ISSUE TITLE
Updated partition constraint for default partition would be violated by some row

### ISSUE THREAD

**Issue by vvitad** [pgpartman/pg_partman#510] opened 2023-03-10 13:03 UTC
I noticed the problem in pg_cron logs. Run_maintenance procedure has been failing since december.
The error it gives:
```
$ select partman.run_maintenance(p_analyze := false);
ERROR:  updated partition constraint for default partition would be violated by some row
CONTEXT: SQL statement "ALTER TABLE table ATTACH PARTITION table_p2022_12 FOR VALUES FROM ('2022-12-01 00:00:00+03') TO ('2023-01-01 00:00:00+03')"
PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,boolean) line 243 at EXECUTE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 283 at assignment
DETAIL:
HINT:
CONTEXT: PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,boolean) line 482 at RAISE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 283 at assignment
DETAIL:
HINT:
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 415 at RAISE

```

Checking last partition of the table table:
table _p2022_10 FOR VALUES FROM ('2022-10-01 00:00:00+03') TO ('2022-11-01 00:00:00+03'),
table _p2022_11 FOR VALUES FROM ('2022-11-01 00:00:00+03') TO ('2022-12-01 00:00:00+03'),

In the error we see that it can't create the next patrition FOR VALUES FROM ('2022-12-01 00:00:00+03') TO ('2023-01-01 00:00:00+03')".

Aftere reading all of the similar issues here I've tried to:
1) create similar to table_default table named part_test
2) copy everything from  table default  to part_test
3) truncate table_default
4) run maintenance
5) no new partitioned has been created, same error.

The same error presists with all the other patritioned table. I am pretty sure that someone accidently ruined it. So now, what I need is:
1) Create all the partitions that was not created.
2) Move data from defaults to the new patriotions.

As I understood I need to use some of the procedures like partition_data_proc and create_parent_id, but I really need help in finding the right order and the correct parameters to give to these procedures. 

There was no example in documentation, only description, and maybe I didn't quite understand them because English is not my native language. 

If I run ` call partman.partition_data_proc(p_parent_table:=table2');` i get one new patrition for the 70s...:
 table2_p1970_01_19 FOR VALUES FROM ('1970-01-19') TO ('1970-01-20'). 

How do I call this procedure if I need to create daily patritions like from 2022-12-01 to 2020-12-02, and so on till 2023-03-13 to 2023-03-14

**Comment by keithf4** [comment] 2023-03-10 23:05
This error occurs when 

 1. data has been inserted into the default partition for some future period of time not covered by current children
 2. normal maintenance tries to create a table that covers any data that exists in the default

First you should evaluate the data that was inserted into the default. If that data is invalid and not needed, you can simply delete the data from the default. If the data is needed, you just have to run the `partition_data_proc()` procedure and that should move any data out of the default and create the necessary child table. 

Since that process will create the necessary child table, the next maintenance runs simply won't have anything to do for a little while. But once the time comes for the next child table to be made, that should then work properly. 

This process is very similar to how migration to native partitioning is done. So you can look at the example calls to `partition_data_proc()` found in the migration doc here https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman_howto_native.md#online-partitioning
A call to `partition_data_proc()` without defining the number of batches you want to run (`p_batch`) will only run a single batch, moving enough to create a single child table. So, if you want to just copy all the data out of the default and create all the necessary children, you can just set the batch number to an arbitrarily high number ( like 200 as I do in the example). It will only run as many batches as are required to move all the data it found.

It is highly recommended to set up monitoring for any data going into the default. The function `check_default()` can help with that. If any data is returned by that function, it means one or more of the partition sets managed by pg_partman has data in the default. See the documentation for it to adjust the kinds of data it returns and how quickly it runs.

If you find this happening frequently, and it is valid data, you'll want to look at increasing the premake value so that future partitions are created to cover the normal range of data you expect to be written at any time.

**Comment by vvitad** [comment] 2023-03-13 12:59
@keithf4 
I managed wiht two promlems but please look at this
Running maintenance gives an error without any detail! 
And there is no constraints on morm_statistic.presence exept ` "presence_pkey" PRIMARY KEY, btree (dt, table_id, date_from, region, standard, telco_id)`


```
# select partman.run_maintenance(p_analyze := false);
ERROR:  updated partition constraint for default partition would be violated by some row
CONTEXT: SQL statement "ALTER TABLE morm_statistic.presence ATTACH PARTITION morm_statistic.presence_p2022_09_01 FOR VALUES FROM ('2022-09-01 00:00:00+03') TO ('2022-09-02 00:00:00+03')"
PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,boolean) line 243 at EXECUTE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 283 at assignment
DETAIL:
HINT:
CONTEXT: PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,boolean) line 482 at RAISE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 283 at assignment
DETAIL:
HINT:
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 415 at RAISE
```

**Comment by vvitad** [comment] 2023-03-14 08:08
I ended up deleting data in the last problematic data and everyhing worked out. Actually typing all day these comments really helped me in achiving this result.

**Comment by vvitad** [comment] 2023-03-27 06:54
@keithf4 oh wow! I didn't know that 0 to timestamp gives out this date.

```
sorm=# select * from partman.part_config where parent_table = 'mytable;'
-[ RECORD 1 ]--------------+-----------------------------------------
parent_table               | mytable
control                    | dt
partition_type             | native
partition_interval         | 1 day
constraint_cols            |
premake                    | 4
optimize_trigger           | 4
optimize_constraint        | 30
epoch                      | none
inherit_fk                 | t
retention                  | 3 year
retention_schema           |
retention_keep_table       | f
retention_keep_index       | t
infinite_time_partitions   | t
datetime_string            | YYYY_MM_DD
automatic_maintenance      | on
jobmon                     | t
sub_partition_set_full     | f
undo_in_progress           | f
trigger_exception_handling | f
upsert                     |
trigger_return_null        | t
template_table             | partman.template_mytable
publications               |
inherit_privileges         | f
constraint_valid           | t
subscription_refresh       |
```
```
                      Table "partman.template_mytable"
  Column   |  Type   | Collation | Nullable | Default | Storage | Stats target | Description
-----------+---------+-----------+----------+---------+---------+--------------+-------------
 dt        | date    |           | not null |         | plain   |              |
 table_id  | integer |           | not null |         | plain   |              |
 date_from | bigint  |           | not null |         | plain   |              |
 date_to   | bigint  |           | not null |         | plain   |              |
 otec_id   | integer |           | not null |         | plain   |              |
 standard  | integer |           | not null |         | plain   |              |
 place     | integer |           | not null |         | plain   |              |
 count     | bigint  | 
```
```
     dt     | table_id |   date_from   |    date_to    | otec_id | standard | place| count
------------+----------+---------------+---------------+----------+----------+--------+--------
 2021-03-16 |        4 | 1584361740000 | 1584361799999 |        1 |        6 |     70 | 765840
 2021-03-16 |        4 | 1584361740000 | 1584361799999 |        1 |        7 |     19 |    318

```

**Comment by vvitad** [comment] 2023-03-27 12:52
Also, @keithf4, could you please give advice concerning running partition_data_proc in production? In testing env it run for about 6 hours for 17 million rows. 
I think its better to point out p_wait.. but other than that?

**Comment by keithf4** [comment] 2023-03-27 18:11
I didn't have any issues with pg_partman handling the sample data you gave here. What version are you running? This was done with the latest stable release (4.7.2).

Without being able to reproduce your issue, I"m not sure what the underlying problem could be. 

Created  a test table with same structure as yours and partitioned the same manner:
```
keith=# create table mytable (dt date not null, table_id integer, date_from bigint, date_to bigint, otec_id int, standard int, place int, count bigint) partition by range (dt);
CREATE TABLE

keith=# select partman.create_parent('public.mytable', 'dt', 'native', 'daily');
 create_parent 
---------------
 t
(1 row)

keith=# \d+ mytable
                                    Partitioned table "public.mytable"
  Column   |  Type   | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
-----------+---------+-----------+----------+---------+---------+-------------+--------------+-------------
 dt        | date    |           | not null |         | plain   |             |              | 
 table_id  | integer |           |          |         | plain   |             |              | 
 date_from | bigint  |           |          |         | plain   |             |              | 
 date_to   | bigint  |           |          |         | plain   |             |              | 
 otec_id   | integer |           |          |         | plain   |             |              | 
 standard  | integer |           |          |         | plain   |             |              | 
 place     | integer |           |          |         | plain   |             |              | 
 count     | bigint  |           |          |         | plain   |             |              | 
Partition key: RANGE (dt)
Partitions: mytable_p2023_03_23 FOR VALUES FROM ('2023-03-23') TO ('2023-03-24'),
            mytable_p2023_03_24 FOR VALUES FROM ('2023-03-24') TO ('2023-03-25'),
            mytable_p2023_03_25 FOR VALUES FROM ('2023-03-25') TO ('2023-03-26'),
            mytable_p2023_03_26 FOR VALUES FROM ('2023-03-26') TO ('2023-03-27'),
            mytable_p2023_03_27 FOR VALUES FROM ('2023-03-27') TO ('2023-03-28'),
            mytable_p2023_03_28 FOR VALUES FROM ('2023-03-28') TO ('2023-03-29'),
            mytable_p2023_03_29 FOR VALUES FROM ('2023-03-29') TO ('2023-03-30'),
            mytable_p2023_03_30 FOR VALUES FROM ('2023-03-30') TO ('2023-03-31'),
            mytable_p2023_03_31 FOR VALUES FROM ('2023-03-31') TO ('2023-04-01'),
            mytable_default DEFAULT
```
Inserted the sample data. It went to the default as expected
```
keith=# insert into mytable values ('2021-03-16', 4, 1234567891025, 1245678912346, 1, 6, 70, 765840);
INSERT 0 1
keith=# insert into mytable values ('2021-03-16', 4, 1234567891023, 1245678912345, 1, 7, 19, 318);
INSERT 0 1
keith=# select * from mytable;
     dt     | table_id |   date_from   |    date_to    | otec_id | standard | place | count  
------------+----------+---------------+---------------+---------+----------+-------+--------
 2021-03-16 |        4 | 1234567891025 | 1245678912346 |       1 |        6 |    70 | 765840
 2021-03-16 |        4 | 1234567891023 | 1245678912345 |       1 |        7 |    19 |    318
(2 rows)

keith=# select * from mytable_default;
     dt     | table_id |   date_from   |    date_to    | otec_id | standard | place | count  
------------+----------+---------------+---------------+---------+----------+-------+--------
 2021-03-16 |        4 | 1234567891025 | 1245678912346 |       1 |        6 |    70 | 765840
 2021-03-16 |        4 | 1234567891023 | 1245678912345 |       1 |        7 |    19 |    318
(2 rows)
```

Ran the procedure to partition it out and it gave the expected output and created the necessary partitions
```
keith=# call partman.partition_data_proc('public.mytable');
NOTICE:  Batch: 1, Rows moved: 2
NOTICE:  Total rows moved: 2
NOTICE:  Ensure to VACUUM ANALYZE the parent (and source table if used) after partitioning data
CALL
keith=# select * from mytable_default;
 dt | table_id | date_from | date_to | otec_id | standard | place | count 
----+----------+-----------+---------+---------+----------+-------+-------
(0 rows)

keith=# select * from mytable;
     dt     | table_id |   date_from   |    date_to    | otec_id | standard | place | count  
------------+----------+---------------+---------------+---------+----------+-------+--------
 2021-03-16 |        4 | 1234567891025 | 1245678912346 |       1 |        6 |    70 | 765840
 2021-03-16 |        4 | 1234567891023 | 1245678912345 |       1 |        7 |    19 |    318
(2 rows)

keith=# \d+ mytable
                                    Partitioned table "public.mytable"
  Column   |  Type   | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
-----------+---------+-----------+----------+---------+---------+-------------+--------------+-------------
 dt        | date    |           | not null |         | plain   |             |              | 
 table_id  | integer |           |          |         | plain   |             |              | 
 date_from | bigint  |           |          |         | plain   |             |              | 
 date_to   | bigint  |           |          |         | plain   |             |              | 
 otec_id   | integer |           |          |         | plain   |             |              | 
 standard  | integer |           |          |         | plain   |             |              | 
 place     | integer |           |          |         | plain   |             |              | 
 count     | bigint  |           |          |         | plain   |             |              | 
Partition key: RANGE (dt)
Partitions: mytable_p2021_03_16 FOR VALUES FROM ('2021-03-16') TO ('2021-03-17'),
            mytable_p2023_03_23 FOR VALUES FROM ('2023-03-23') TO ('2023-03-24'),
            mytable_p2023_03_24 FOR VALUES FROM ('2023-03-24') TO ('2023-03-25'),
            mytable_p2023_03_25 FOR VALUES FROM ('2023-03-25') TO ('2023-03-26'),
            mytable_p2023_03_26 FOR VALUES FROM ('2023-03-26') TO ('2023-03-27'),
            mytable_p2023_03_27 FOR VALUES FROM ('2023-03-27') TO ('2023-03-28'),
            mytable_p2023_03_28 FOR VALUES FROM ('2023-03-28') TO ('2023-03-29'),
            mytable_p2023_03_29 FOR VALUES FROM ('2023-03-29') TO ('2023-03-30'),
            mytable_p2023_03_30 FOR VALUES FROM ('2023-03-30') TO ('2023-03-31'),
            mytable_p2023_03_31 FOR VALUES FROM ('2023-03-31') TO ('2023-04-01'),
            mytable_default DEFAULT
```

**Comment by keithf4** [comment] 2023-05-08 02:21
Just checking to see if the advice above helped at all and if you still need any further assistance

**Comment by keithf4** [comment] 2023-05-19 15:22
I'll be closing this issue for now. If you still need assistance, please feel free to re-open it and I can try to help further

**Closed by keithf4** 2023-05-19 15:22 UTC
Labels: question, requires submitter response
