### ISSUE TITLE
Delete cascade from unpartitioned table on run_maintenance()

### ISSUE THREAD

**Issue by aleosd** [pgpartman/pg_partman#365] opened 2021-06-08 14:57 UTC
I have partitioned table (native range by date) that is referenced from another unpartitioned table with `ON DELETE CASCADE`:

```
CREATE TABLE ds.batch_search_requests (
  id UUID NOT NULL, 
  created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
  name TEXT, 
  request JSON NOT NULL, 
  PRIMARY KEY (id, created_at)
)
PARTITION BY RANGE (created_at)
	
CREATE INDEX ix_ds_batch_search_requests_id ON ds.batch_search_requests (id)

CREATE TABLE ds.batch_search_tasks (
  id SERIAL NOT NULL, 
  created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
  name TEXT NOT NULL, 
  request_id UUID, 
  request_created_at TIMESTAMP WITH TIME ZONE, 
  PRIMARY KEY (id), 
  FOREIGN KEY(request_id, request_created_at) REFERENCES ds.batch_search_requests (id, created_at) ON DELETE CASCADE
)
```

When I run simple `delete from batch_search_requests` all corresponding records from the second table are removed. However, when partition is dropped with `select partman.run_maintenance();` corresponding records are left in second table and foreign keys replaced with `null`. 

Is there a way to enforce this constraints (on delete cascade) when dropping partition?

**Comment by aleosd** [comment] 2021-06-08 15:05
Partman configs:

```sql
SELECT partman.create_parent(
    'ds.batch_search_requests',
    'created_at',
    'native',
    'daily',
    p_premake := 7,
    p_start_partition := (CURRENT_TIMESTAMP-'14 days'::interval)::text
)

UPDATE partman.part_config SET
        retention = '14 days',
        retention_keep_table = FALSE,
        retention_keep_index = FALSE,
        infinite_time_partitions = TRUE,
        optimize_trigger = 7
WHERE parent_table = 'ds.batch_search_requests'
```

I've noticed that after initial partitions creation I have corresponding reference record on every partition:
```
Referenced by:
    TABLE "ds.batch_search_tasks" CONSTRAINT "batch_search_tasks_request_id_request_created_at_fkey6" FOREIGN KEY (request_id, request_created_at) REFERENCES ds.batch_search_requests_p2021_05_30(id, created_at) ON DELETE CASCADE
```
However, after `select partman.run_maintenance()` those reference is removed

**Comment by keithf4** [comment] 2021-07-05 16:26
The issue is that the drop command is using "CASCADE" which allows the table to be dropped and removes any existing FK relations. 

https://github.com/pgpartman/pg_partman/blob/master/sql/functions/drop_partition_time.sql#L196

It used to be that you could only reference child tables directly, so that worked fine in that case. The option to reference the parent table for FKs  hadn't existed when the maintenance code for pg_partman was originally written and hasn't had any updates since then. 

I'll try and see if I can add an option in to make the CASCADE disabled by default but able to be turned off if desired.

**Comment by keithf4** [comment] 2021-07-26 20:51
This will be fixed in next release. Do not have an ETA on that yet.

**Closed** 2021-11-17 21:37 UTC
Labels: confirmed bug, fixed in current release
