### ISSUE TITLE
Partion_data_time not working when more than one partitioned table in DB (PG12)

### ISSUE THREAD

**Issue by JorgeFMorais** [pgpartman/pg_partman#295] opened 2020-01-27 07:30 UTC
The function _partition_data_time()_ can be executed with a different number of input parameters. Currently, when executed with no parameters _partition_data_time()_ the function attemps to partition the data of all the partitioned tables configured in the DB. 

However, this currently raises an error if the partitioned tables have different column structures. When executing the function mutiple times for each single table it works as expected.

I believe the problem is due to the temp table **partman_temp_data_storage** not being dropped when the no parameter verision of the function is called.

I have not tested the function _partition_data_id()_ but I assume its affected in the same way.

**Comment by keithf4** [comment] 2020-01-27 15:30
I'm a bit confused about this because you should not be able to call `partition_data_time/id()` without giving a parent table name. It should show a unknown function error because no function exists with a full empty or all default parameter list
```
keith@keith=# select partman.partition_data_time();
ERROR:  function partman.partition_data_time() does not exist
LINE 1: select partman.partition_data_time();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Time: 6.079 ms
```

Also, even if it made it past that error somehow, the function itself is not programmed to iterate over the entire list of partitioned tables in the partman config anyway. 

However, the temp table still sticking around is a valid concern. I'll see if I can fix that.

Can you give me a repeatable set of steps to reproduce this scenario so I can see what's going on?

**Comment by JorgeFMorais** [comment] 2020-01-27 16:16
I'm sorry I didn't explain the error correctly. The problem is caused when calling the `partition_data_*` function multiple times in the same connection for different partitioned tables.

Since the temp table is not dropped until the connection is closed, when trying to move the data of the original table to the `partman_temp_data_storage` temp table an error is raised. This is due to the temp table still having the structure of the previous table that called the `partition_data_*`  function.

**Comment by keithf4** [comment] 2020-01-27 16:23
That makes more sense and does sound like a bug. Should hopefully just need to add a drop table statement for the temp table into those functions then as a fix. Will try and have that implemented for next release if that solves the issue. Thanks!

**Comment by keithf4** [comment] 2020-02-02 16:12
Fix for this is in my "migrate" branch if you want to test it out - https://github.com/pgpartman/pg_partman/tree/migrate

**Closed** 2020-02-03 07:16 UTC
Labels: confirmed bug, fixed in next release
