### ISSUE TITLE
PG partman installation

### ISSUE THREAD

**Issue by Hiram2018** [pgpartman/pg_partman#234] opened 2018-10-17 15:01 UTC
I try to install pg_partman on centos 7, but when i run make install The installer send me  "Makefile:42: *** Minimum version of PostgreSQL required is 9.4.0.  Stop.", But I have installed Postgres 9.6 and Postgres 10 in two different ports...

What can I do?

Thanks

Hiram

**Comment by keithf4** [comment] 2018-10-17 15:45
Sounds like whichever version of `pg_config` is in your current path is not at least version 9.4.

**Comment by Hiram2018** [comment] 2018-10-17 15:57
Hi ,

                I check my pg_version file an it is 9.6 , but I have pg installed in another path /postgres/data/…

 

                But I comment the lines:

#DATA = $(wildcard updates/*--*.sql) sql/$(EXTENSION)--$(EXTVERSION).sql

#EXTRA_CLEAN = sql/$(EXTENSION)--$(EXTVERSION).sql

#else

#$(error Minimum version of PostgreSQL required is 9.4.0)

                In the makefile and it work fine.

 

                But now I can not find the  'pg_partman_bgw' file … to charge “shared_preload_libraries”…

:(

If you cant help me please…

 

Kind Regards,

Hiram

 

 

 

De: Keith Fiske [mailto:notifications@github.com] 
Enviado el: miércoles, 17 de octubre de 2018 12:46
Para: pgpartman/pg_partman <pg_partman@noreply.github.com>
CC: Hiram2018 <hiram.walker@bermann.cl>; Author <author@noreply.github.com>
Asunto: Re: [pgpartman/pg_partman] PG partman installation (#234)

 

Sounds like whichever version of pg_config is in your current path is not at least version 9.4.

**Comment by Hiram2018** [comment] 2018-10-17 15:57
Hi ,
	I check my pg_version file an it is 9.6 , but I have pg installed in another path /postgres/data/…

	But I comment the lines:
#DATA = $(wildcard updates/*--*.sql) sql/$(EXTENSION)--$(EXTVERSION).sql
#EXTRA_CLEAN = sql/$(EXTENSION)--$(EXTVERSION).sql
#else
#$(error Minimum version of PostgreSQL required is 9.4.0)
	In the makefile and it work fine.

	But now I can not find the  'pg_partman_bgw' file … to charge “shared_preload_libraries”…

If you cant help me please…

Kind Regards,
Hiram

**Comment by keithf4** [comment] 2018-10-17 16:04
You shouldn't need to edit the makefile at all for things to work. If you have to do that, there's nothing I can really do to help at this point unfortunately.

Check the version of `pg_config`
```
pg_config --version
```
I tested on my system, and make is working fine for 9.6. So there is something wrong with whichever versions of the postgres binaries & libraries that are in your PATH
```
$ pg_config --version
PostgreSQL 9.6.10

$ make 
cat sql/types/types.sql sql/tables/tables.sql sql/functions/apply_cluster.sql sql/functions/apply_constraints.sql sql/functions/apply_foreign_keys.sql sql/functions/apply_privileges.sql sql/functions/apply_publications.sql sql/functions/autovacuum_off.sql sql/functions/autovacuum_reset.sql sql/functions/check_control_type.sql sql/functions/check_name_length.sql sql/functions/check_parent.sql sql/functions/check_subpart_sameconfig.sql sql/functions/check_subpartition_limits.sql sql/functions/create_function_id.sql sql/functions/create_function_time.sql sql/functions/create_parent.sql sql/functions/create_partition_id.sql sql/functions/create_partition_time.sql sql/functions/create_sub_parent.sql sql/functions/create_trigger.sql sql/functions/drop_constraints.sql sql/functions/drop_partition_column.sql sql/functions/drop_partition_id.sql sql/functions/drop_partition_time.sql sql/functions/inherit_template_properties.sql sql/functions/partition_data_id.sql sql/functions/partition_data_time.sql sql/functions/reapply_privileges.sql sql/functions/run_maintenance.sql sql/functions/show_partition_info.sql sql/functions/show_partition_name.sql sql/functions/show_partitions.sql sql/functions/stop_sub_partition.sql sql/functions/undo_partition.sql > sql/pg_partman--4.0.0.sql
#
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fPIC -I. -I./ -I/opt/pgsql9610/include/server -I/opt/pgsql9610/include/internal -D_GNU_SOURCE   -c -o src/pg_partman_bgw.o src/pg_partman_bgw.c -MMD -MP -MF .deps/pg_partman_bgw.Po
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fPIC -L/opt/pgsql9610/lib   -Wl,--as-needed -Wl,-rpath,'/opt/pgsql9610/lib',--enable-new-dtags  -shared -o src/pg_partman_bgw.so src/pg_partman_bgw.o
```

**Comment by Hiram2018** [comment] 2018-10-17 16:22
Yes you are 

I check my postgres version
Last login: Tue Oct 16 17:37:25 EDT 2018 on pts/0
-bash-4.2$ pg_config --version
**PostgreSQL 9.2.24**
-bash-4.2$ psql -c "select version()"
                                                 version
----------------------------------------------------------------------------------------------------------
 **PostgreSQL 9.6.8** on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit

It don´t make sense...

**Comment by keithf4** [comment] 2018-10-17 16:32
Looks like you have the default version of PostgreSQL provided by the CentOS repos installed (9.2). If you're not using 9.2, I recommend uninstalling those packages.

Also, not sure how you have 9.6 and 10 installed, but if you use the community repository packages, installing those should automatically update the default version of PG in your path to be the most recent. 

https://www.postgresql.org/download/linux/redhat/

**Comment by Hiram2018** [comment] 2018-10-17 16:38
Thanks Keith, I will re-install pg 9.6 and check pg_config. I will send you feedback.

Kind regards

Hiram

**Comment by Hiram2018** [comment] 2018-10-23 19:00
Hi Keith,

I reinstall postgres, install cmake and the pg_config was restored to pg 9.6, I crete the schema find, but when i run  CREATE EXTENSION pg_partman SCHEMA partman; i had this error
ERROR:  syntax error at or near "PROCEDURE"...

Which is the script that is given me the error? (could be "pg_partman--3.2.1--4.0.0" ?)

thanks in advance,
Hiram

**Comment by Hiram2018** [comment] 2018-10-25 20:44
Hi Keith,

 

I reinstall postgres, install cmake and the pg_config was restored to pg 9.6, I create the schema find, 

but when i run CREATE EXTENSION pg_partman SCHEMA partman; 

i had this error
ERROR: syntax error at or near "PROCEDURE"...

 

What can I do?

 

Best regards!

Hiram

 

 

 

De: Keith Fiske [mailto:notifications@github.com] 
Enviado el: miércoles, 17 de octubre de 2018 13:32
Para: pgpartman/pg_partman <pg_partman@noreply.github.com>
CC: Hiram2018 <hiram.walker@bermann.cl>; Author <author@noreply.github.com>
Asunto: Re: [pgpartman/pg_partman] PG partman installation (#234)

 

Looks like you have the default version of PostgreSQL provided by the CentOS repos installed (9.2). If you're not using 9.2, I recommend uninstalling those packages.

Also, not sure how you have 9.6 and 10 installed, but if you use the community repository packages, installing those should automatically update the default version of PG in your path to be the most recent.

https://www.postgresql.org/download/linux/redhat/

**Comment by Hiram2018** [comment] 2018-10-25 20:50
Hi Keith,

I install postgres96* in a new server
 install cmake and gcc, etc, 
I create the schema without any issue, 
but when i run script:
CREATE EXTENSION pg_partman SCHEMA partman; 
i had this error
ERROR: syntax error at or near "PROCEDURE"...

What can I do?

Best regards!
Hiram

**Comment by Hiram2018** [comment] 2018-10-26 15:21
Hi Keith

 

I uninstall pg_partman (Latest 4.0), download and install versión 3.1, re install and evething Works fine!

 

Thanks for your help, have a nice day

Hiram

 

De: Keith Fiske [mailto:notifications@github.com] 
Enviado el: jueves, 25 de octubre de 2018 22:27
Para: pgpartman/pg_partman <pg_partman@noreply.github.com>
CC: Hiram2018 <hiram.walker@bermann.cl>; Author <author@noreply.github.com>
Asunto: Re: [pgpartman/pg_partman] PG partman installation (#234)

 

You really need to be careful with which version of PostgreSQL is in your PATH when you have multiple major version installed. It should only attempt to install PROCEDUREs if you run make with PG11 binaries in your PATH. What is the result when you run pg_config from the same terminal that you compile pg_partman from? My result with 9.6 is below and appears to be working properly.

$ pg_config
BINDIR = /opt/pgsql9610/bin
DOCDIR = /opt/pgsql9610/share/doc
HTMLDIR = /opt/pgsql9610/share/doc
INCLUDEDIR = /opt/pgsql9610/include
PKGINCLUDEDIR = /opt/pgsql9610/include
INCLUDEDIR-SERVER = /opt/pgsql9610/include/server
LIBDIR = /opt/pgsql9610/lib
PKGLIBDIR = /opt/pgsql9610/lib
LOCALEDIR = /opt/pgsql9610/share/locale
MANDIR = /opt/pgsql9610/share/man
SHAREDIR = /opt/pgsql9610/share
SYSCONFDIR = /opt/pgsql9610/etc
PGXS = /opt/pgsql9610/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/opt/pgsql9610' '--enable-depend' '--enable-cassert' '--enable-debug' '--with-openssl'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/opt/pgsql9610/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.6.10
$ make install
$ psql
psql (9.6.10)
Type "help" for help.
 
keith@keith=# create extension pg_partman schema partman;
CREATE EXTENSION
Time: 140.009 ms
keith@keith=# \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description                        
--------------------+---------+------------+-----------------------------------------------------------
 pg_partman         | 4.0.0   | partman    | Extension to manage partitioned tables by time or ID
 pg_stat_statements | 1.4     | public     | track execution statistics of all SQL statements executed
 pgstattuple        | 1.4     | public     | show tuple-level statistics
 pgtap              | 0.98.0  | public     | Unit testing for PostgreSQL
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(5 rows)

**Comment by keithf4** [comment] 2018-10-26 16:06
Installing an older version really isn't the ideal solution. I found out what the problem is, though.

In CentOS7, the pg_config binary is not in the default PATH of any user, so when you try and run `make` it throws an error and still creates the extension sql file but without properly filtering out the PROCEDUREs

```
$ make
/bin/sh: pg_config: command not found
/bin/sh: pg_config: command not found
make: pg_config: Command not found
cat sql/types/types.sql sql/tables/tables.sql sql/functions/apply_cluster.sql sql/functions/apply_constraints.sql sql/functions/apply_foreign_keys.sql sql/functions/apply_privileges.sql sql/functions/apply_publications.sql sql/functions/autovacuum_off.sql sql/functions/autovacuum_reset.sql sql/functions/check_control_type.sql sql/functions/check_name_length.sql sql/functions/check_parent.sql sql/functions/check_subpart_sameconfig.sql sql/functions/check_subpartition_limits.sql sql/functions/create_function_id.sql sql/functions/create_function_time.sql sql/functions/create_parent.sql sql/functions/create_partition_id.sql sql/functions/create_partition_time.sql sql/functions/create_sub_parent.sql sql/functions/create_trigger.sql sql/functions/drop_constraints.sql sql/functions/drop_partition_column.sql sql/functions/drop_partition_id.sql sql/functions/drop_partition_time.sql sql/functions/inherit_template_properties.sql sql/functions/partition_data_id.sql sql/functions/partition_data_time.sql sql/functions/reapply_privileges.sql sql/functions/run_maintenance.sql sql/functions/show_partition_info.sql sql/functions/show_partition_name.sql sql/functions/show_partitions.sql sql/functions/stop_sub_partition.sql sql/functions/undo_partition.sql sql/procedures/partition_data_proc.sql sql/procedures/reapply_constraints_proc.sql sql/procedures/run_maintenance_proc.sql sql/procedures/undo_partition_proc.sql > sql/pg_partman--4.0.0.sql
```
If you then go and force that file in place it will throw the error that you're seeing since the Makefile wasn't able to run properly to filter out the PROCEDUREs on versions older than 11.

The way to fix this is to ensure the path to `pg_config` is in your current PATH
```
PATH=/usr/pgsql-9.6/bin:$PATH
```
This is an issue with CentOS distros because they keep the `pg_config` binary out of the normal user PATHs. Not much I can do about that on my end unfortunately. pg_partman is made available in the PGDG repo, so I'd recommend installing it from there if possible. Not sure they have 4.0.0 available there yet, though

https://www.postgresql.org/download/linux/redhat/

**Comment by Hiram2018** [comment] 2018-10-26 18:55
Keith,

 

                I try the installation fixin the path as you said, but does not work, so I think to use an earlier versión of partman an work fine.

 

Kind regards,

 

Hiram 

 

 

De: Keith Fiske [mailto:notifications@github.com] 
Enviado el: viernes, 26 de octubre de 2018 13:06
Para: pgpartman/pg_partman <pg_partman@noreply.github.com>
CC: Hiram2018 <hiram.walker@bermann.cl>; Author <author@noreply.github.com>
Asunto: Re: [pgpartman/pg_partman] PG partman installation (#234)

 

Installing an older version really isn't the ideal solution. I found out what the problem is, though.

In CentOS7, the pg_config binary is not in the default PATH of any user, so when you try and run make it throws an error and still creates the extension sql file but without properly filtering out the PROCEDUREs

$ make
/bin/sh: pg_config: command not found
/bin/sh: pg_config: command not found
make: pg_config: Command not found
cat sql/types/types.sql sql/tables/tables.sql sql/functions/apply_cluster.sql sql/functions/apply_constraints.sql sql/functions/apply_foreign_keys.sql sql/functions/apply_privileges.sql sql/functions/apply_publications.sql sql/functions/autovacuum_off.sql sql/functions/autovacuum_reset.sql sql/functions/check_control_type.sql sql/functions/check_name_length.sql sql/functions/check_parent.sql sql/functions/check_subpart_sameconfig.sql sql/functions/check_subpartition_limits.sql sql/functions/create_function_id.sql sql/functions/create_function_time.sql sql/functions/create_parent.sql sql/functions/create_partition_id.sql sql/functions/create_partition_time.sql sql/functions/create_sub_parent.sql sql/functions/create_trigger.sql sql/functions/drop_constraints.sql sql/functions/drop_partition_column.sql sql/functions/drop_partition_id.sql sql/functions/drop_partition_time.sql sql/functions/inherit_template_properties.sql sql/functions/partition_data_id.sql sql/functions/partition_data_time.sql sql/functions/reapply_privileges.sql sql/functions/run_maintenance.sql sql/functions/show_partition_info.sql sql/functions/show_partition_name.sql sql/functions/show_partitions.sql sql/functions/stop_sub_partition.sql sql/functions/undo_partition.sql sql/procedures/partition_data_proc.sql sql/procedures/reapply_constraints_proc.sql sql/procedures/run_maintenance_proc.sql sql/procedures/undo_partition_proc.sql > sql/pg_partman--4.0.0.sql

If you then go and force that file in place it will throw the error that you're seeing since the Makefile wasn't able to run properly to filter out the PROCEDUREs on versions older than 11.

The way to fix this is to ensure the path to pg_config is in your current PATH

PATH=/usr/pgsql-9.6/bin:$PATH

This is an issue with CentOS distros because they keep the pg_config binary out of the normal user PATHs. Not much I can do about that on my end unfortunately. pg_partman is made available in the PGDG repo, so I'd recommend installing it from there if possible. Not sure they have 4.0.0 available there yet, though

https://www.postgresql.org/download/linux/redhat/

**Comment by keithf4** [comment] 2018-10-26 20:09
The problem with sticking with an older version for this reason is that you will never be able to get bug fixes or new features in pg_partman, of which there are several in 4.0.0. You really should try to get the binary pathing issues straightened out on this system if it is going to be used for long term production.

**Comment by Hiram2018** [comment] 2018-11-07 19:49
Hi Keith,

 

  I would like to know if pg_partman support partitioning between two
diferents servers.

 

Something like this:



 

Thanks in advance  

Best regards,

 

Hiram

**Comment by keithf4** [comment] 2018-11-08 16:59
Appears you missed an attachment or something is wrong in your code formatting?

pg_partman itself doesn't currently support and foreign data wrappers or remote data connections. If you're looking for a sharding solution, you might want to take a look at the citus extension: https://www.citusdata.com/product/community  
It actually uses pg_partman under the hood for some of the partitioning it does.

**Comment by keithf4** [comment] 2019-02-07 21:46
Closing this issue for now. If you have any further questions regarding the PATH issue, feel free to reopen. Otherwise please make a new issue.

**Closed by keithf4** 2019-02-07 21:46 UTC
Labels: question
