### ISSUE TITLE
Tests failures if using PG 15 for homebrew's test

### ISSUE THREAD

**Issue by Porkepix** [pgpartman/pg_partman#498] opened 2022-12-18 09:04 UTC
As I was routinely bumping Homebrew's formulas and saw `pg_partman` was  compatible with PG 15 I tried to change the dependency along the bump here: https://github.com/Homebrew/homebrew-core/pull/118375

However, this resulted in tests breakages, for which a revert back to PG 14 fixed things, as visible in the PR.

The encountered problems:

```
  ==> /opt/homebrew/opt/postgresql@15/bin/pg_ctl start -D /private/tmp/pg_partman-test-20221217-42317-mwjc46/test -l /private/tmp/pg_partman-test-20221217-42317-mwjc46/log
  Error: test failed
  waiting for server to start.... stopped waiting
  pg_ctl: could not start server
```

And then from the log file:
```
2022-12-17 11:48:47.453 EST [2754] LOG:  database system is shut down
2022-12-17 11:54:57.146 EST [24460] FATAL:  could not access file "pg_partman_bgw": No such file or directory
2022-12-17 11:54:57.146 EST [24460] LOG:  database system is shut down
```

**Comment by keithf4** [comment] 2022-12-18 22:59
It looks like the shared_preload_libraries portion was set for pg_partman, but that library did not get put into place properly. Without seeing why the test actually failed or why the background worker portion failed, I can't help too much more here.

**Comment by Porkepix** [comment] 2022-12-19 08:15
Well, here's the whole test that's run: https://github.com/Porkepix/homebrew-core/blob/894ddf03c176b75fde621288949dafcc894a2dcd/Formula/pg_partman.rb#L35-L52

There are info from the CI visible directly from GitHub and I think @chenrui333 posted the useful parts from logs I posted above; don't know what else could be added?

**Comment by keithf4** [comment] 2022-12-19 17:25
The error you're getting isn't anything specific to pg_partman. It's a general failure for any library added to `shared_preload_libraries` but the actual library file not being installed on the file system in the expected location.

It appears that whatever is installing/building pg_partman for 15 is not putting the library file in place. Without seeing how that process works or what errors might be occurring during the installation of that library file, I can't really help anymore. I do not use homebrew myself so I cannot run these tests to see.

**Comment by keithf4** [comment] 2022-12-19 19:41
I'm happy to help however I can, but I cannot see where the build or install process steps are logged in your homebrew testing. If you can point them out I can look further.

**Comment by keithf4** [comment] 2023-01-12 16:25
If you are still having this issue, is there anything else you can provide as to why the build is failing? Otherwise I will be closing this during my next issue review.

**Comment by Porkepix** [comment] 2023-01-12 18:07
I can't tell much more than what's visible here: https://github.com/Homebrew/homebrew-core/actions/runs/3719435551/jobs/6308326268 and the fact it uses https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/tests.yml and https://github.com/Homebrew/homebrew-core/blob/master/Formula/pg_partman.rb

Above that, @chenrui333 would know a lot more I think, especially I can't go and see on the runners.
Another solution would be for you try a build from sources on your computer through homebrew, I guess?

**Comment by keithf4** [comment] 2023-03-10 23:24
Apologies I haven't responded here for a bit. I don't run Mac so I don't have homebrew easily available to use. Just looking at this

https://github.com/Homebrew/homebrew-core/blob/master/Formula/pg_partman.rb#L28

It does look like it tries to account for putting the library file in place. 

If you go to look at the system after homebrew runs, do you see the library file in place? 

```
$ /usr/pgsql-15/bin/pg_config | grep LIBDIR
LIBDIR = /usr/pgsql-15/lib
```
```
$LIBDIR/pg_partman_bgw.so
```
Does it have the proper permissions set to allow the PG user to read/use it? Example from mine:
```
-rwxr-xr-x 1 root root   71816 Dec 16 12:12 pg_partman_bgw.so
```
So without seeing any additional details of why it might not be copying that file I can't really assist anymore here. Hopefully someone else with homebrew experience might be able to provide some more insight

**Comment by dahu33** [comment] 2023-04-26 02:42
I bet the issue is the homebrew formula installed the `pg_partman_bgw.so` only in the postgresql@14 `LIBDIR`. Not sure if we can modify the formula to install pg_partman on any installed version of postgresql on the system.

See:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/pg_partman.rb#L21
https://github.com/Homebrew/homebrew-core/blob/master/Formula/pg_partman.rb#L28

**Comment by keithf4** [comment] 2023-04-26 04:37
That would certainly do it! Thank you for the tip @dahu33

**Comment by keithf4** [comment] 2023-05-19 15:25
With that found, I think the solution to this issue is something that needs to be done upstream with homebrew. Please open an issue on their Github repo for further assistance.

If it turns out there's something else i need to do on my end to help with fixing this, please feel free to re-open this issue and I'll investigate further.

Will be closing for now.

**Closed by keithf4** 2023-05-19 15:25 UTC
Labels: help wanted
