### ISSUE TITLE
Automated child table triggers (WAS: Inherit DELETE/UPDATE triggers from parent)

### ISSUE THREAD

**Issue by davidblewett** [pgpartman/pg_partman#42] opened 2014-12-17 00:42 UTC
Currently, DELETE and UPDATE triggers that are defined on the parent will be silently ignored if they trigger action in a child table. INSERT triggers fire correctly, but from what I can tell, DELETE/UPDATE do not at all. I'm trying to automate updating an external system on changes to any data in the child tables. I can create them manually, but it would be great if pg_partman did it when it created new partitions.

**Comment by keithf4** [comment] 2016-06-24 15:30
See if RULES can be handled here as well. See https://github.com/keithf4/pg_partman/issues/121

**Comment by 1803** [comment] 2016-07-01 09:39
**Trigger inheritance:**

_This is still WIP._

Side note: to make sure the `before insert` partitioning trigger fires last (we don't want to override any default value triggers etc.) it is suggested to name it z_[table_name]_[suffix].

**Concept:**

1. Not all triggers should be inherited;
2. There is no reason to create two or more triggers with different names, but calling the same trigger function on the same condition (`tgtype`);
3. There is no need to use `when` clause in triggers since all the checks can be done inside the trigger function (just for simplicity);
_4. There are situations when trigger function code might need to be adjusted (for example my case with `update` might use this feature); [not impletemented]_
_5. Triggers may change, thus a function is needed that can remove triggers and/or functions; [not impletemented]_
_6. New child-tables can be added and triggers should be applied to them automatically; [not implemented]_

As a result:

There's a table `referencing part_config(parent_name)` that keeps list of triggers for each parent table. It also stores the trigger type (`consistent` - same trigger function for all tables, `custom` - trigger function should be created for each table). For custom triggers an additional field is used that stores function source and name prefix. The point of custom functions is to adjust trigger code for each table (in my case for performance reasons).

Trigger creation is done in a stored procedure that uses a for cycle that checks if the trigger with same tgtype and function exists on each table of parittion.

Some changes need to be done to `run_maintenance` function to reflect the need to create triggers for newly created child-tables

User should specify the triggers that need to be inherited by adding a corresponding row to the `part_trigger` table.

Here's the code:

http://pastebin.com/w3jzQBDu

Keep in mind: for test case you need to create extension, then apply the patch and then proceed.

**Comment by keithf4** [comment] 2016-07-01 16:04
Looks very interesting so far! Just did a quick overview so far and didn't really dig into exactly how it all works, but just some notes for now.

- Please separate out your timezone changes from this. That is a different issue and any changes related to that should go into their own change set.

- Use the same naming patterns for variables I have been doing already. Just makes it easier to see how things fit together if the same naming conventions are used.

- One thing that was a concern for me that has delayed my working on this is that the ordering of trigger firing should not be based solely on the trigger name. Yes, that just happens to be the convention of how postgres fires the triggers, but if you read any developer comments on the topic, it's not something that should be relied upon because it is not any sort of set standard for how postgres internals are always intended to work. That functionality could go away at any time. The response to this is generally to rewrite your triggers so one's firing does not depend on another's firing before it. When you have control of your trigger function source, this is generally pretty easy. But in the case of partitioning, and how it has to be done with triggers in postgres, it's much harder because you never know what the end user will do. Honestly don't have a solution for it myself either, and your use of a custom name does present a possible solution using the alphabetical ordering currently in place. But it isn't ideal long term. Just something to keep in mind and why I've been hesitant on trying to support this. As you've seen, it brings an incredible amount of complexity and may just be the cause of more issues for people.

**Comment by 1803** [comment] 2016-07-01 19:10
Yeah at first I was trying to follow the same naming convention but I'm just too used to the one I use. Anyway I will edit it sometime tomorrow morning also removing timezone related stuff just to make it less confusing. I just needed an example of custom trigger and I couldn't think of anything that is simple enough both to implement and to understand.

**Comment by agentgt** [comment] 2017-05-07 03:44
For what its worth for others that land here I got my trigger to work by making it lexically before the partman triggers based on Keith's earlier comment

> Edit: Just realized, you may actually see some parent triggers fire "properly" if they are also BEFORE triggers and come before the pg_partman trigger name alphabetically. Triggers are fired in alphabetical order. May not work as you expect, though.

For some reason I find the reliance on lexical ordering a little disturbing but it works for now. That is the partman triggers get called after mine and seem to work.

**Comment by keithf4** [comment] 2017-05-07 15:06
Just to keep anyone that's looking for this feature informed, I'm hoping to revist this once PostgreSQL 10 comes out. Since there is no longer a user-facing trigger that controls where data goes, I think this will work much better there. There is still discussion on the final implementation of how triggers on native partition sets will actually be handled, so I'm waiting to see how that turns out. At this time, I have no plans on supporting triggers without native partitioning. The firing order when using a trigger for partitioning just seems like to much of a hassle to try and handle.

**Comment by bclennox** [comment] 2018-04-16 21:48
Is this still planned to be supported in a future release? In our case, we would like triggers on the template table for native partitioning to be copied to the child tables, similar to indexes and foreign keys. If not, we can handle it in a separate maintenance task.

**Comment by keithf4** [comment] 2018-04-17 18:14
I'll see if I can look into this again, but I just haven't had the time unfortunately. If your own separate maintenance task to apply the triggers from the template table works, I would be curious to see it. Might be able to incorporate it.

**Comment by WhiteWind** [comment] 2019-07-11 06:18
> I would be curious to see it

Me too!

**Comment by ignaski** [comment] 2019-12-03 14:40
Apologies if this is not the correct place for this message. 
I am trying to move from no partitioning to native partitioning and struggling with 'before' trigger. Postgres only allows 'after' triggers on partitioned tables. It is only possible to add 'before' trigger on the child table. I need this trigger to update the audit column 'updated_at'. Maybe anyone here have already found a way to achieve this? Many thanks

**Comment by keithf4** [comment] 2022-08-12 15:16
Closing this issue for now. Will see how things are with triggers during my refactor when trigger based partitioning is working, but this is a bit out of scope for pg_partman at this time.

**Closed by keithf4** 2022-08-12 15:16 UTC
Labels: feature request
