### ISSUE TITLE
inherit_template_properties PG10 inheritance issue

### ISSUE THREAD

**Issue by KevMurph** [pgpartman/pg_partman#300] opened 2020-03-06 06:20 UTC
https://github.com/pgpartman/pg_partman/blob/258679998659f7f3d2fb75b0d870eb19ff8296f6/sql/functions/inherit_template_properties.sql#L156

The above line has given me some problems in the past on PG10, but I've been able to resolve it by swapping it out the section of code with something like below. I believe it has something to do with having having indexes on a separate tablespace from the parent table / partitions.

ELSE
-- statement column should be just the portion of the index definition that defines what it actually is
    v_sql := format('CREATE %s INDEX ON %I.%I %s', CASE WHEN v_index_list.indisunique = TRUE THEN 'UNIQUE' ELSE '' END, v_child_schema, v_child_tablename,v_index_list.statement);
    IF v_index_list.tablespace_name IS NOT NULL 
THEN
       -- v_sql := v_sql || format(' TABLESPACE %I', v_index_list.tablespace_name);
       execute format('set default_tablespace = %s',  v_index_list.tablespace_name );
    END IF;
    RAISE NOTICE 'Create index: %', v_sql;
    EXECUTE v_sql;
    reset default_tablespace;
END IF;

Here is the error message:
db=# SELECT partman.run_maintenance(p_analyze:=false);
ERROR:  syntax error at or near "TABLESPACE"
CONTEXT: PL/pgSQL function inherit_template_properties(text,text,text) line 156 at EXECUTE
SQL statement "SELECT partman.inherit_template_properties(p_parent_table, v_parent_schema, v_partition_name)"
PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,boolean) line 228 at PERFORM
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 280 at assignment
DETAIL:
HINT:
CONTEXT: PL/pgSQL function create_partition_time(text,timestamp with time zone[],boolean,boolean) line 459 at RAISE
PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 280 at assignment
DETAIL:
HINT:
CONTEXT:  PL/pgSQL function partman.run_maintenance(text,boolean,boolean,boolean) line 398 at RAISE

**Comment by keithf4** [comment] 2020-04-08 21:47
I'm having some trouble reproducing this error. This TAP test 

https://github.com/pgpartman/pg_partman/blob/master/test/test_native/tablespace/test-time-daily-native-tablespace-template.sql

hits that code path and produces this statement in my logs (with log level set to debug) to create the index in the specified tablespace

```
2020-04-08 17:22:44.521 EDT [[local]] [7934]: [l-23] user=keith,db=keith,app=psql,e=00000 DEBUG:  Create index: CREATE UNIQUE INDEX ON partman_test.time_taptest_table_p2020_04_04  USING btree (col2) TABLESPACE mytablespace
```
If you can give me a set of steps to reproduce this error, I'd be happy to look into it further

**Comment by keithf4** [comment] 2020-05-05 21:38
Please let me know if you're still having this issue. And if so, please provide a means of reproducing this issue.

**Comment by KevMurph** [comment] 2020-05-11 21:28
Hey Keith,

I am still having this issue with one of the partitioned tables in one of my environments. 

Basically, I have one table where if I disable automatic_maintenance in the part_config table, then run_maintenance runs fine. The part_config entry for this table looks almost identical to the rest of my entries, except for the parent_table and template_table.

In looking at the parent / partitioned tables, there is nothing that jumps out as being substantively different across the tables. None of the tables I am comparing have unique constraints, and all of them have indexes that appear on a separate tablespace.

The other odd thing about this issue is that is seems so sporadic. We can go months without having a problem with run_maintenance for this table in any of our environments, and then suddenly this error will crop up in what seems to be a random environment.

It seems to always be this table, for one reason or another. Do you have any ideas?

**Comment by keithf4** [comment] 2020-05-14 16:17
Can you please provide the schema for the partitioned table that you are encountering this issue with along with the configuration for it contained in the `part_config` table? 

You provided a PR with a potential fix, which I appreciate, but if you believe this is due to a specific index format that is causing it, I need to see what that potential index format may be.

**Comment by KevMurph** [comment] 2020-05-14 16:29
Hey, thanks for following up--I'd love to provide the schema, but unfortunately it's from work and it's extremely unlikely they'd allow me to provide the DDL.

I have had a heck of a time manually reproducing this error. It seems to just pop up randomly every couple / few months... I've now applied the patch in all of our environments, so none of them are breaking right now, but I'm going to speak with my team about reverting the code on one of our internal environments in the hopes that it breaks again soon. When that happens, I can add some additional logging into the function to grab exactly which CREATE INDEX statement it is failing on. Hopefully that will illuminate something.

I totally respect your aversion to adding a bug fix in for a bug that you can't replicate--I'd feel the same way! I'll close the linked PR for now and reopen it in the future if appropriate based on what I've outlined here.

**Comment by keithf4** [comment] 2020-05-14 16:39
Sounds good. Feel free to rename any objects as needed. I just need the matching structure and partman configuration.

**Comment by keithf4** [comment] 2021-01-20 21:57
Just checking in one more time to see if this is still an issue and you are able to provide something to reproduce this error? If not, I will be closing this issue in a few weeks.

**Closed** 2021-02-10 21:33 UTC
Labels: requires submitter response
