### ISSUE TITLE
not initialized menber of struct BackgroundWorker

### ISSUE THREAD

**Issue by kimi7iceman** [pgpartman/pg_partman#573] opened 2023-09-16 00:40 UTC
Hello.

BackgroundWorker menber <bgw_type> is not initialized on pg_partman's source.
Looks like this menber is added from [PostgreSQL v11](https://www.postgresql.org/docs/11/bgworker.html).

I noticed this because of  invalid byte sequence error when i tried to import [csvlog file to table](https://www.postgresql.org/docs/14/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-CSVLOG).

**Comment by keithf4** [comment] 2023-09-16 00:46
I'm sorry I'm not following the issue you are having. Can you provide a set of steps to follow to reproduce the error your encountering as well as the actual errors from your logs?

**Comment by keithf4** [comment] 2023-09-16 00:50
Nevermind, I think I see what you're saying. There's a new item in the BGW struct for `type`. I'll if I can fix that. Odd that I hadn't run into that myself so far.

**Comment by kimi7iceman** [comment] 2023-09-16 01:44
Thank you and sorry.

> Odd that I hadn't run into that myself so far.

Me too. I have machines of three version pairs, and only the third occurs.
I checked the pg_partman and postgresql sources that might have something to do with log output, and it didn't look like anything had changed over the years.

```
1. postgresql 14.4 x pg_partman 4.6.7
2. postgresql 14.6 x pg_partman 4.7.0
3. postgresql 14.9 x pg_partman 4.7.3
```

It may have something to do with the glibc version, etc., but I don't know.

However, I checked the source around logging in postgresql, and it seemed to refer to bgw_type.
In function get_backend_type_for_log() at postgres/src/backend/utils/error/elog.c.

I rebuilt it with partman's source, setting bgw_type to the same value as bgw_name, and tried to use it.
Then, the value set for code's bgw_type was output as log item's backend_type and no problem occurred.

**Comment by keithf4** [comment] 2023-09-16 01:52
Sounds good. I'll have that fixed in 5.x. Haven't heard any complaints on this before so not going to worry about backporting to 4.x for now.

**Comment by kimi7iceman** [comment] 2023-09-16 02:02
> I'll have that fixed in 5.x. 

Thank you.

**Comment by keithf4** [comment] 2023-09-18 19:40
So if I had debug logging turned on, I now see where that  type was being used and I do see those odd characters being entered into the logs. 
```
2023-09-18 15:32:03.690 EDT [2023-09-18 15:31:53 EDT]  [750310] user=,db=,app=,err=00000,sess=6508a5a9.b72e6: DEBUG:  background worker "'????" (PID 750354) exited with exit code 0
```
Maybe that's the difference between the systems is the log level you have it set at.
Since I actually have different background workers in partman, I set the type to a more generic name and it comes out like this now. The dynamic one reports the `name` value while the exit report uses the type.
```
2023-09-18 15:33:51.199 EDT [2023-09-18 15:33:51 EDT]  [750655] user=,db=,app=,err=00000,sess=6508a61f.b743f: DEBUG:  unregistering background worker "pg_partman dynamic background worker (dbname=keith)"
2023-09-18 15:33:51.199 EDT [2023-09-18 15:33:51 EDT]  [750655] user=,db=,app=,err=00000,sess=6508a61f.b743f: DEBUG:  background worker "pg_partman background worker" (PID 750665) exited with exit code 0
```
Thanks again for reporting this!

**Comment by keithf4** [comment] 2023-09-28 19:15
Version 5.0.0 has been released with this fix in the BGW. May have to restart the database to see the updated library in effect after the update.
Thanks again!

**Closed** 2023-10-26 15:14 UTC
Labels: confirmed bug, fixed in current release
